"""empty message

Revision ID: 01f9d42a98c2
Revises: 10ec2e769d32
Create Date: 2018-04-06 22:00:07.440234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f9d42a98c2'
down_revision = '10ec2e769d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='cms_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'cms_user', ['email'], unique=True)
    # ### end Alembic commands ###
