"""empty message

Revision ID: ce2cf8e219db
Revises: ac712f23c0f9
Create Date: 2018-04-06 21:03:10.886007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2cf8e219db'
down_revision = 'ac712f23c0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role_user', sa.Column('cms_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('cms_role_user_ibfk_1', 'cms_role_user', type_='foreignkey')
    op.create_foreign_key(None, 'cms_role_user', 'cms_user', ['cms_user_id'], ['id'])
    op.create_foreign_key(None, 'cms_role_user', 'cms_role', ['cms_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.create_foreign_key('cms_role_user_ibfk_1', 'cms_role_user', 'cms_user', ['cms_role_id'], ['id'])
    op.drop_column('cms_role_user', 'cms_user_id')
    # ### end Alembic commands ###
